#!/bin/bash
set -o verbose
set -e

##############
## homebrew ##
##############
brew update
brew upgrade

###########
## emacs ##
###########
curl -I https://elpa.gnu.org/
curl -I https://melpa.org/
curl -I http://orgmode.org/elpa/
curl -I http://joseito.republika.pl/sunrise-commander/

pushd ~/elisp/cider
git fetch --prune --all
git rebase upstream/master

rm -rf cider-pkg.el
make elpaclean
make elpa
popd

pushd ~/.emacs.d
rm -rf .cask/
cask
cask link cider ~/elisp/cider
popd
