#!/bin/bash
set -e

brew update
brew upgrade

pushd ~/elisp/cider
rm -rf cider-pkg.el
make elpaclean
make elpa
popd

pushd ~/.emacs.d
rm -rf .cask/
cask upgrade
cask
cask link cider ~/elisp/cider
popd
