#!/bin/bash
set -o verbose
set -e

brew update
brew upgrade

pushd ~/elisp/cider
git fetch --prune --all
git rebase upstream/master

rm -rf cider-pkg.el
make elpaclean
make elpa
popd

pushd ~/.emacs.d
rm -rf .cask/
cask upgrade
cask
cask link cider ~/elisp/cider
popd
